# Generated by Django 5.2.4 on 2025-07-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(blank=True, choices=[('Progress', 'Progress'), ('Completed', 'Completed')], default='Progress', max_length=20, null=True),
        ),
    ]
