# Generated by Django 5.2.4 on 2025-07-16 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=150)),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.DurationField()),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='files')),
                ('description', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='courses.course')),
            ],
        ),
    ]
