# Generated by Django 5.2.4 on 2025-07-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_lesson_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('order', 'course')},
        ),
    ]
