# Generated by Django 5.2.4 on 2025-07-18 04:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_video_url_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
