# Generated by Django 5.2.4 on 2025-07-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.tag'),
        ),
    ]
